=== MichalZar/My-Hobby/projekt.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
	<xs:element name="hipertext">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="wrapper" type="wrapperType" minOccurs="1"/>
				<xs:element name="autor" type="autorType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="autorType" mixed="true">
		<xs:sequence>
			<xs:element name="rok" type="rokType"/>
			<xs:element name="znacznik" type="krotki_napis"/>
			<xs:element name="dane">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="imie" type="krotki_napis"/>
						<xs:element name="nazwisko" type="krotki_napis"/>
						<xs:element name="kierunek">
							<xs:simpleType>
								<xs:restriction base="dlugi_napis">
									<xs:enumeration value="Informatyka"/>
									<xs:enumeration value="Elektronika i Telekomunikacja"/>
									<xs:enumeration value="Inżynieria danych"/>
									<xs:enumeration value="Inżynieria biomedyczna"/>
									<xs:enumeration value="Automatyka, cybernetyka i robotyka"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="grupa" type="grupaType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="osoba" type="krotki_napis"/>
	</xs:complexType>
	
	<xs:simpleType name="rokType">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="4"/> 
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="wrapperType">
		<xs:sequence>
			<xs:element ref="tytul" minOccurs="0"/>
			<xs:element name="menu">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="linki" type="linkiType" minOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="content" type="contentType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:simpleType name="grupaType">
		<xs:restriction base="xs:byte">
			<xs:maxInclusive value="7"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:element name="tytul" type="dlugi_napis"/>

	<xs:simpleType name="krotki_napis">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30"/>
			<xs:minLength value="2"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="dlugi_napis">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="contentType" mixed="true">
		<xs:sequence>
			<xs:element ref="tytul" minOccurs="0"/>
			<xs:element name="spis">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="linki" type="linkiType" minOccurs="1"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="sekcja" type="sekcjaType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="sekcjaType">
		<xs:sequence>
			<xs:group ref="Grupa"/>
		</xs:sequence>
		<xs:attribute name="rodzaj">
			<xs:simpleType>
				<xs:restriction base="krotki_napis">
					<xs:pattern value="KS|OM|MW"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>

	<xs:group name="Grupa">
		<xs:sequence>
			<xs:element ref="tytul" minOccurs="1"/>
			<xs:element name="tresc" type="xs:string" minOccurs="0"/>
			<xs:element name="lista" type="listaType" minOccurs="0"/>
			<xs:element name="tabela" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="wiersz" type="wierszType" minOccurs="1" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>

	<xs:complexType name="listaType">
		<xs:sequence>
			<xs:element name="linki" type="linkiType" minOccurs="1"/>
		</xs:sequence>
		<xs:attribute name="kolarstwo" type="krotki_napis"/>
	</xs:complexType>

	<xs:complexType name="wierszType">
		<xs:sequence>
			<xs:element name="kolumna" type="kolumnaType" minOccurs="1" maxOccurs="3"/>
		</xs:sequence>
		<xs:attribute name="w" type="ilosc"/>
	</xs:complexType>

	<xs:complexType name="kolumnaType">
		<xs:simpleContent>	
			<xs:extension base="xs:string">
				<xs:attribute ref="id"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>

	<xs:complexType name="linkiType">
		<xs:sequence>
			<xs:element name="link" type="linkType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="id"/>
	</xs:complexType>

	<xs:attribute name="id" type="ilosc"/>

	<xs:simpleType name="ilosc">
		<xs:restriction base="xs:integer">
			<xs:minInclusive value="1"/>
			<xs:maxInclusive value="5"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="linkType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute name="zrodlo" type="xs:anyURI"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
</xs:schema>

=== MichalZar/My-Hobby/projektt.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE hipertext [
	<!ELEMENT hipertext (wrapper,autor)>
	<!ELEMENT wrapper (tytul,menu,content)>
	<!ELEMENT tytul (#PCDATA)>
	<!ELEMENT menu (linki)>
	<!ELEMENT linki (link*)>
	<!ELEMENT link (#PCDATA)>
	<!ELEMENT content (tytul,spis,sekcja+)>
	<!ELEMENT spis (linki)>
	<!ELEMENT sekcja (tytul,tresc?,lista?,tabela?)>
	<!ELEMENT tresc (#PCDATA)>
	<!ELEMENT lista (linki)>
	<!ELEMENT tabela (wiersz*)>
	<!ELEMENT wiersz (kolumna*)>
	<!ELEMENT kolumna (#PCDATA)>
	<!ELEMENT autor (rok,znacznik,dane)>
	<!ELEMENT rok (#PCDATA)>
	<!ELEMENT znacznik (#PCDATA)>
	<!ELEMENT dane (imie,nazwisko,kierunek,grupa)>
	<!ELEMENT imie (#PCDATA)>
	<!ELEMENT nazwisko (#PCDATA)>
	<!ELEMENT kierunek (#PCDATA)>
	<!ELEMENT grupa (#PCDATA)>
	<!ATTLIST hipertext xmlns:xsi CDATA #REQUIRED>
	<!ATTLIST hipertext xsi:noNamespaceSchemaLocation CDATA #REQUIRED>
	<!ATTLIST linki id CDATA #REQUIRED>
	<!ATTLIST link zrodlo CDATA #REQUIRED>
	<!ATTLIST sekcja rodzaj (KS|OM|MW) #REQUIRED>
	<!ATTLIST autor osoba CDATA 'student'>
	<!ATTLIST lista kolarstwo CDATA #IMPLIED>
	<!ATTLIST wiersz w CDATA #REQUIRED>
	<!ATTLIST kolumna id CDATA #REQUIRED>
	<!ENTITY znaczek "Copyright">
	]>
<?xml-stylesheet type= "text/xsl" href="projekt.xsl"?>
<hipertext xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="projekt.xsd">
	<wrapper>
		<tytul>Kolarstwo - Moje Hobby</tytul>
		<menu>
			<linki id="1">
					<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/projekt.html">Strona główna</link>
					<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/galeria.html">Galeria zdjęć</link>
					<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/kontakt.html">Kontakt</link>
			</linki>
		</menu>
		<content>
			<tytul>Spis tresci</tytul>
			<spis>
				<linki id="2">
						<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/projekt.html#KS">Słów kilka o kolarstwie</link>
						<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/projekt.html#OM">O mnie</link>
						<link zrodlo="file:///C:/Users/Micha%C5%82/Desktop/projekt%20HiH/HTML%20+%20CSS/projekt.html#MW">Wyniki</link>
				</linki>
			</spis>
			<sekcja rodzaj="KS">
				<tytul>Słów kilka o kolarstwie</tytul>
				<tresc>
					Mówi się, że punkt widzenia zależy od punktu siedzenia, dotyczy to róznież kolarstwa. Jedni traktują rower jako dobry środek transportu do pracy lub szkoły, inni widzą w tym pasję i hobby. Choziaż wydawać by się mogło, że kolarstwo to mało interesujący sport to jest zupełnie na odwrót. Jest to nietuzinkowa i dość wyjątkowa dyscyplina. Wymaga wiele techniki, wytrzymałości i samozaparcia. Wbrew pozorom jest również niebezpieczna, a trudne trasy wymagają sporego doświadczenia. Jednakże po sporej ilości godzin na siodełku, można dostrzec jaką frajdę i ile satysfakcji daje nam jazda na rowerze. Rower zabierze nas także w miejsca niezwykłe i oszałamiające. Poznamy sekrety natury i przeżyjemy wiele przygod. W tym sporcie każdy znajdzie coś dla siebie, gdyż w dzisiejszych czasach istnieje bardzo dużo rodzajów kolarstwa m.in.:
				</tresc>
				<lista kolarstwo="rodzaje">
					<linki id="3">
							<link zrodlo="https://pl.wikipedia.org/wiki/Kolarstwo_szosowe">kolarstwo szosowe</link>
							<link zrodlo="https://pl.wikipedia.org/wiki/Kolarstwo_górskie">kolarstwo górskie</link>
							<link zrodlo="https://pl.wikipedia.org/wiki/Kolarstwo_przełajowe">kolarstwo przełajowe</link>
							<link zrodlo="https://pl.wikipedia.org/wiki/Kolarstwo_torowe">kolarstwo torowe</link>
					</linki>
				</lista>
			</sekcja>
			<sekcja rodzaj="OM">
				<tytul>O mnie</tytul>
				<tresc>
					Kolarstwem nie interesowałem się od zawsze. Zostałem raczej zmotywowany, przez mojego tatę do podjęcia się treningów. Po nieciekawym wypadku na rowerze w 2017 roku, postanowiłem przekuć porażkę w zwyciestwo i zacząłem jeździć nie tylko rekreacyjnie. Okazło się, że kolarstwo górskie było strzałem w dziesiątkę. Po pół roku wystartowałem w pierwszych zawodach,a rok póżniej zdobyłem swoje pierwsze podium. Dołączyłem do lokalnego klubu kolarskiego, w którym spotkałem wiele ciekawych i spragnionych jazdy osób. Nigdy nie myślałem nad tym, aby wziąść się za kolarstwo na bardziej profesjonalnym poziomie. Od zawsze jeździłem jako amator i myślę, że nadal będę to robił, gdyż jazda na rowerze sprawia mi niesamowitą frajdę.
				</tresc>
			</sekcja>
			<sekcja rodzaj="MW">
				<tytul>Wyniki</tytul>
				<tabela>
					<wiersz w="1">
						<kolumna id="1">Sezon</kolumna> 
						<kolumna id="2">Pozycja w kategorii open</kolumna> 
						<kolumna id="3">Pozycja w kategorii wiekowej</kolumna>
					</wiersz>
					<wiersz w="2">
						<kolumna id="1">2018</kolumna>
						<kolumna id="2">61</kolumna>
						<kolumna id="3">9</kolumna>
					</wiersz>
					<wiersz w="3">
						<kolumna id="1">2019</kolumna>
						<kolumna id="2">17</kolumna>
						<kolumna id="3">2</kolumna>
					</wiersz>
					<wiersz w="4">
						<kolumna id="1">2020</kolumna>
						<kolumna id="2">51</kolumna>
						<kolumna id="3">2</kolumna>
					</wiersz>
					<wiersz w="5">
						<kolumna id="1">2021</kolumna>
						<kolumna id="2">22</kolumna>
						<kolumna id="3">3</kolumna>
					</wiersz>
				</tabela>
			</sekcja>
		</content>
	</wrapper>
	<autor osoba="student">
		<rok>2021</rok>
		<znacznik>&znaczek;</znacznik>
		<dane>
			<imie>Michał</imie>
			<nazwisko>Zaranko</nazwisko>
			<kierunek>Elektronika i Telekomunikacja</kierunek>
			<grupa>1</grupa>
		</dane>
	</autor>
</hipertext>
